## Benchmark window 2

```{r}
#| output: false
# online
# remotes::install_github("r-spatialecology/landscapemetrics@basemetrics3")
# remotes::install_github("r-spatialecology/landscapemetrics@commoncalcs")
# or locally
devtools::install("~/Software/landscapemetrics3")
devtools::install("~/Software/landscapemetrics")
```

```{r}
landscape <- terra::rast(landscapemetrics::augusta_nlcd)
# landscape <- terra::disagg(landscape, 4)
# landscape <- terra::aggregate(landscape, 4, fun = "modal")
```

```{r}
whats <- c("lsm_l_ent")
```


```{r}
window2 <- matrix(1, nrow = 15, ncol = 15)
bench::mark(landscapemetrics::window_lsm(landscape, window = window2, what = whats),
            landscapemetrics3::window_lsm(landscape, window = window2, what = whats),
            iterations = 1)
```

```{r}
landscape2 <- terra::rast(landscapemetrics::landscape)
# landscape <- terra::disagg(landscape, 4)
# landscape <- terra::aggregate(landscape, 4, fun = "modal")
```

```{r}
window <- matrix(1, nrow = 3, ncol = 3)
bench::mark(landscapemetrics::window_lsm(landscape2, window = window, what = whats),
            landscapemetrics3::window_lsm(landscape2, window = window, what = whats),
            iterations = 10, check = FALSE)
```
